[features]
skip-lint = false
[programs.mainnet]
rnsdid_core = "3WaA2C9VRHczjqcdVgWw8Ug2VfoCVbCzEp9bwPPG6Qj6"
[programs.devnet]
rnsdid_core = "3WaA2C9VRHczjqcdVgWw8Ug2VfoCVbCzEp9bwPPG6Qj6"
[programs.testnet]
rnsdid_core = "3WaA2C9VRHczjqcdVgWw8Ug2VfoCVbCzEp9bwPPG6Qj6"
[programs.localnet]
rnsdid_core = "3WaA2C9VRHczjqcdVgWw8Ug2VfoCVbCzEp9bwPPG6Qj6"

[registry]
url = "https://anchor.projectserum.com"


[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"



[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/1_initialize_collection.test.ts"
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/2_collection_config.test.ts"
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/3_authorize_mint.test.ts"
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/4_airdrop.test.ts"
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/5_burn.test.ts"
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/6._fetch_metadata_edtion.test.ts"


[test]
startup_wait = 50000

[test.validator]
# url = "https://api.devnet.solana.com"
# url = "https://api.testnet.solana.com"
url = "https://api.mainnet-beta.solana.com"

[[test.validator.clone]]
address = "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL" # associated-token

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s" # token-metadata

[[test.validator.clone]]
address = "BGUMAp9Gq7iTEuizy4pqaxsTyUCBK68MDfK752saRPUY" # bubblegum

[[test.validator.clone]]
address = "noopb9bkMVfRPU8AsbpTUg8AQkHtKwMYZiFUjNRtMmV" # noop

[[test.validator.clone]]
address = "cmtDvXumGCrqC1Age74AVPhSRVXJMd8PJS91L8KbNCK" # account compression
