[features]
skip-lint = false
[programs.mainnet]
rnsdid_core = "5eqvLvpg16iTZ1q3V8BtjmcLWSiBuv4tZXXvvfqKYHA7"
[programs.devnet]
rnsdid_core = "5eqvLvpg16iTZ1q3V8BtjmcLWSiBuv4tZXXvvfqKYHA7"
[programs.testnet]
rnsdid_core = "5eqvLvpg16iTZ1q3V8BtjmcLWSiBuv4tZXXvvfqKYHA7"
[programs.localnet]
rnsdid_core = "5eqvLvpg16iTZ1q3V8BtjmcLWSiBuv4tZXXvvfqKYHA7"

[registry]
url = "https://anchor.projectserum.com"


[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 50000

[test.validator]
url = "https://api.devnet.solana.com"
